Input.cs Completed
Stevie-Goodman/CMP1903M-Assessment1 pull request #7
Opened 2022-03-18 12:33 UTC by Stevie-Goodman

I've completed the code for Input.cs.
Would appreciate testing of file input in a Windows environment.

Thanks

**Update Log**
Resolves #1

2022-03-21 15:29 UTC, Lynx-At0Mic commented
Looks good! When testing in a windows environment multi-line and null inputs were handled correctly in both file and keyboard text input modes. File input mode also handles invalid file paths correctly.

One possible issue I found involves keyboard input mode. The asterisk used to terminate input in keyboard input mode is not removed by `ManualTextInput()`. This could cause problems when analysing the text later on. My suggestion would be to remove the last character in the string before returning with something like `textInput = textInput.Remove(textInput.Length - 1);` before returning as the asterisk will always be present on `textInput` after input is terminated.

2022-03-22 12:14 UTC, Stevie-Goodman commented
@Lynx-At0Mic, I've added `.Trim('*');` to line 59.
You can see that in my review below your comment.
Thanks for the feedback.

2022-03-23 14:08 UTC, Stevie-Goodman commented
I've completed the code for Analyse.cs.
Would appreciate a review of the code.

Thanks.

2022-03-23 17:29 UTC, Lynx-At0Mic requested changes
Nice work! Other than sentence analysis (see comment), the code runs as expected in a windows environment

2022-03-23 17:29 UTC, Lynx-At0Mic commented on Input.cs
> +        textInput = textInput.Trim().Trim('*'); // Trims final input to remove whitespace before first character.
Looks good!

2022-03-23 17:29 UTC, Lynx-At0Mic commented on Analyse.cs
> +        Sentences = Regex.Matches(Input, @"[.!?]\s").Count + 1; // Counts every ". " and deducts 1.
The number of sentences is still 1 if nothing is entered by the user or the file is empty. This also returns 2 if a single sentence is entered with a full stop and whitespace after. One way of fixing this could be to check for a line beginning or whitespace before the sentence and either whitespace or ending punctuation. Consider replacing the regex expression with something like `(\s|^)+[^.!?]*([.!?]|\S)`

2022-03-23 21:24 UTC, Stevie-Goodman commented
Complete code for Report.cs.
Would appreciate a review.

Thanks.

2022-03-23 21:25 UTC, Stevie-Goodman commented on Analyse.cs
> +        Sentences = Regex.Matches(Input, @"[.!?]\s").Count + 1; // Counts every ". " and deducts 1.
Will look into this tomorrow when I polish the rest of my code.

Thanks for the review.

2022-03-24 14:50 UTC, Stevie-Goodman commented on Analyse.cs
> +        Sentences = Regex.Matches(Input, @"[.!?]\s").Count + 1; // Counts every ". " and deducts 1.
@Lynx-At0Mic, I believe the issue is now fixed.
Do you mind quickly confirming for me?

Thanks.

2022-03-24 16:18 UTC, Lynx-At0Mic commented on Analyse.cs
> +        Sentences = Regex.Matches(Input, @"[.!?]\s").Count + 1; // Counts every ". " and deducts 1.
Looks like the issue still persists when using file input. On `Input.cs` line 67 you have `textInput = textInput.Trim(' ', '*');` which solves the whitespace after ending punctuation on manual text input. However, this is not present in the method `FileTestInput()`. Adding `textInput = textInput.Trim(' ', '*');` to the end of `FileTestInput()` should solve this issue.

2022-03-24 22:58 UTC, Stevie-Goodman commented on Analyse.cs
> +        Sentences = Regex.Matches(Input, @"[.!?]\s").Count + 1; // Counts every ". " and deducts 1.
Wow, that's embarrassing.
Can't believe I forgot that.
Fixed now, thanks for the help. 👍

2022-03-30 10:32 UTC, merged